[tool.poetry]
name = "vtuber-backend"
version = "0.1.0"
description = "VTuber merch management system backend"
authors = ["malingsuo <djsojdn1285@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.139.2"
uvicorn = {extras = ["standard"], version = "^0.51.0"}
sqlalchemy = "^2.0.51"
alembic = "^1.18.5"
psycopg = {extras = ["binary"], version = "^3.3.4"}
pydantic-settings = "^2.14.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
