"""username globally unique

Revision ID: 0153d9a7d3b0
Revises: d25d4e65a8a3
Create Date: 2026-07-19 23:40:04.788607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0153d9a7d3b0'
down_revision: Union[str, Sequence[str], None] = 'd25d4e65a8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 與 PostgreSQL 預設的 unique 約束命名規則相同：<表>_<欄1>_<欄2>_key
USERS_UQ_NAMING = {"uq": "%(table_name)s_%(column_0_N_name)s_key"}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 初始 migration 建的 UNIQUE(company_id, username) 沒取名字：PostgreSQL 自動
    # 命名為 users_company_id_username_key，SQLite 則真的沒有名字。
    # naming_convention 讓 batch 模式反射 SQLite 的表時補上同一個名字，才刪得到
    with op.batch_alter_table('users', naming_convention=USERS_UQ_NAMING) as batch_op:
        batch_op.drop_constraint('users_company_id_username_key', type_='unique')
        batch_op.create_unique_constraint('uq_users_username', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.create_unique_constraint('users_company_id_username_key', ['company_id', 'username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
