"""username globally unique

Revision ID: 0153d9a7d3b0
Revises: d25d4e65a8a3
Create Date: 2026-07-19 23:40:04.788607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0153d9a7d3b0'
down_revision: Union[str, Sequence[str], None] = 'd25d4e65a8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_company_id_username_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_company_id_username_key'), 'users', ['company_id', 'username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
