"""products.item_type_id nullable for bundles

Revision ID: 7bcdd42a9d02
Revises: 6dc1f3a5fd0e
Create Date: 2026-07-19 14:12:08.803314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcdd42a9d02'
down_revision: Union[str, Sequence[str], None] = '6dc1f3a5fd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不支援 ALTER COLUMN，batch 模式改用「建新表→搬資料→換名」；
    # PostgreSQL 上仍是同一句 ALTER TABLE
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('item_type_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('item_type_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
    # ### end Alembic commands ###
