"""companies.is_active for tenant suspension

Revision ID: d25d4e65a8a3
Revises: 7bcdd42a9d02
Create Date: 2026-07-19 17:54:44.169282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25d4e65a8a3'
down_revision: Union[str, Sequence[str], None] = '7bcdd42a9d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 既有公司一律視為啟用中，所以帶 server_default
    op.add_column(
        'companies',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_active')
    # ### end Alembic commands ###
